[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["cd backend && npm ci && cd ../frontend && npm ci"]

[phases.build]
cmds = ["cd backend && npx prisma generate && npm run build && cd ../frontend && npm run build && cp -r www ../backend/public"]

[start]
cmd = "cd backend && npm run start"
